### ISSUE TITLE
Expired quests are shown as expired on boost page 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#488]
https://www.loom.com/share/56fb1b9401744077b406abeabb3ff926

**Comment by ktarun1419** [comment]
I've reviewed the code and identified that the problem lies within the API https://api.starknet.quest/boost/get_boosts. The key "expired" is not being received, resulting in an undefined value. As a consequence, the element remains clickable and displays data even after expiration.
<img width="574" alt="Screenshot 2024-02-01 at 12 14 19 PM" src="https://github.com/starknet-id/starknet.quest/assets/86646398/7dcc3e29-771b-43e8-8adc-b6d0dd9456a7">

There are two possible solutions for this issue:

1. Address the problem in the frontend by checking the expiration time and adding the key accordingly.

2. Alternatively, incorporate the key in the backend, which would automatically resolve the bug.
Please assign this bug to me so that i can solve this

**Comment by ktarun1419** [comment]
Can you please let me know why did you closed my request ? Is there any issue?

**Comment by Marchand-Nicolas** [comment]
We need to add the "expired" field on the API: https://github.com/starknet-id/api.starknet.quest/pull/193

**Comment by ktarun1419** [comment]
Okk ,Thanks @Marchand-Nicolas

**Comment by Marchand-Nicolas** [comment]
Done here https://github.com/starknet-id/api.starknet.quest/pull/193
