### ISSUE TITLE
Leaderboard XP points miscalculation 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#505]
Hello , 
I think there is some miscalculation in Xp distribution 
In this video I am sharing my own wallets 

ARGENTX : 0x05462bd07DF5Cd8223ED55457DBACC34839f300eE7486aEdDdeB0976b465B911
BRAAVOS : 0x054e0ab67bd384312d640915b55d7e918fe2031269ec26f8fc7fde9abbd1e0a5

https://www.loom.com/share/a73f0fcc91264837a32ac6368befdc7c

**NOTE : All the Quest NFT were minted and none of them purchased from both the wallets**

**Comment by ayushtom** [comment]
Hi @revengexd , I looked through this issue 
Thank you for the video and the description!

The xp points are as follows  -
Argent  - 390
Braavos - 395 

The extra points in braavos wallet is of the Second Focus Tree quest which gave it a boost. The argent wallet in this case  didn't do this quest and has lesser points because of it.
Although the extra achievement is there in the argent wallet account but unfortunately the quests held more points than the extra achievement you had on argent. Hence the final difference being of 5 points more for Braavos

The reason you don't see the NFT on the lands page for your braavos wallet is that - this particular quest didnt have a nft reward assigned to it. You had to manually claim the NFT on the focus tree wallet. So it's not coming up in you braavos wallet right now but you have been awarded points for it on the leaderboard eventhough you didnt get an NFT on the braavos wallet which is connected to starknet quest

**Comment by ayushtom** [comment]
@revengexd  Let me know if you have any other questions and we can close the issue

**Comment by revengexd** [comment]
Hey @ayushtom 
Thank you for the detail explanation 
Quest's with no NFT have messed me up ,Sorry 
We can close the issue
