### ISSUE TITLE
Featured Quest shows randomly different quest when wallet connected !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#553]
https://www.loom.com/share/9c56311596fd4933a6ecc11f9dc24e08?sid=815d4c7c-8197-4289-af4e-679490f51698

**Comment by JeffreyJoel** [comment]
Hi @revengexd, can I work on this?

**Comment by revengexd** [comment]
> Hi @revengexd, can I work on this?

Issues labelled with **open for contribution** are available for you to pick up.

**Comment by JeffreyJoel** [comment]
Okay, thank you.

**Comment by ayushtom** [comment]
@revengexd on discussing with the product team we came to the conclusion that this could come under `bugs which become feature` since this would also us to show other quests which the user can participate in. On reloading the featured quest changes to something random might be a good way to keep the users engaged and hence i believe we can close this issue. Nice catch tho!
