### ISSUE TITLE
Buggy Margin top quiz

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#669]
## Description 

In the quiz section, the margin is not big enough between the logo + name section and the question. 

Please add a  `margin-top : 1rem` for it to render better.

Deadline: 1 business day after assignment. 

<img width="309" alt="Capture d’écran 2024-05-03 à 13 27 41" src="https://github.com/starknet-id/starknet.quest/assets/78437165/68041ae8-35f0-4d5e-9923-db3bf5f16cac">

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by raizo07** [comment]
Hello @fricoben @ayushtom I'll like to work on this.

**Comment by fricoben** [comment]
Gave it to @raizo07 as his first issue with us

**Comment by raizo07** [comment]
Hi @fricoben , I am unable to test if my fix works because I keep getting this when I want to start a quiz
<img width="835" alt="image" src="https://github.com/starknet-id/starknet.quest/assets/81079370/3b97613e-3c81-43dc-aed8-18424420ef5a">
I already own a starknet domain by the way, which is connected to my braavos id
