### ISSUE TITLE
Typography component

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#694]
refer #693

**Comment by Naomi-Gift** [comment]
@ayushtom Can i hop on this?

To address this issue, I'd start by defining a clear interface for the props associated with the text component, outlining the specifications for each text tag. Next, I'd design the component itself to incorporate these text tags or predefined styles, as indicated in the Figma file. This setup would ensure that the correct text style is dynamically applied based on the specified typography types.

**Comment by martinvibes** [comment]
@ayushtom i would like to hop on this

**Comment by abdulqaharu** [comment]
@ayushtom I would like to work on this issue

**Comment by lindsaymoralesb** [comment]
Hi! @ayushtom I'm a Software Engineer based in Costa Rica. I work as a full-stack, but most of my experience is on frontend development.
I would use the approach of atomic design development and this is how i would tackle this issue:
1. I will create an interface to define the props that the typography component can receive.
2. After that, I will create the typography component, using the props interface created before so that it is a completely dynamic and reusable component.
3. I will create the different styles defined on the figma and also an enum to have the available typography types - with those I would know which style to apply to the text.

**Comment by Dprof-in-tech** [comment]
hi @ayushtom , I'm Isaac a contributor to the starknet quest project and I would love to work on this task.

I would tackle this issue by first creating a type interface for the props to the text component noting the specifications for each text tag, then I would create the component itself to use these text tags or defined styles as shown in the figma file to have the available typography types so that the appropriate text style would be dynamically applied to the text 

I will be awaiting your response

**Comment by VictoriaAde** [comment]
I would like to work on this.

**Comment by ayushtom** [comment]
@lindsaymoralesb assigning to you!
