### ISSUE TITLE
Add Skeleton to the `Earn` page 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#777]
# Issue description

When going to https://starknet.quest/discover/defi we have a text `loading...` to show the user that the content of the table is loading. 

<img width="1440" alt="Capture d’écran 2024-07-31 à 11 47 43" src="https://github.com/user-attachments/assets/072e094d-2974-45ae-bcdd-f764c75e97ab">

I would like to use a custom skeleton instead. 

## Steps 

- [ ] Create a `defiTableSkeletong.tsx` component that represents a skeleton of the size of the table (10 lines)
- [ ] Add it to `defiTable.tsx` 
- [ ] Make sure the skeleton renders well on mobile and laptop before raising the PR

**Comment by Ugo-X** [comment]
Hello Project Lead @fricoben ! I'm Ugo, a full-stack (js,React,Node,Next.js,Three.js,nest.js) developer with a strong track record in OD  projects. I've been actively involved since Edition 1 of OD hack, contributing to various initiatives.
Having used OnlyDust extensively, I'm confident in my ability to tackle new challenges.
I'm eager to leverage my skills and experience to contribute effectively.
my profile link: https://app.onlydust.com/u/Ugo-X

please can i be assigned this issue @fricoben

**Comment by od-hunter** [comment]
D

**Comment by raizo07** [comment]
@fricoben can I work on this

**Comment by mexes20** [comment]
Hello @fricoben Can I take this as my first contribution?

**Comment by fricoben** [comment]
Assigned to @Ugo-X

**Comment by Ugo-X** [comment]
> Assigned to @Ugo-X

Thank you, will work on it and be sure to relay updates on my progress.
