### ISSUE TITLE
Cursor issue over the page 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#805]
https://www.loom.com/share/636cf7224e244b7fbfc3584b1faada56?sid=ebe8385c-c868-4ad2-a696-b10bbbb5ae0d

The cursor changes from the Starknet Quest custom pointer to the regular pointer when we pass on these sections

**Comment by Iwueseiter** [comment]
Hi @revengexd can I work on this?

**Comment by GoSTEAN** [comment]
hello @revengexd let me work on this and get it done asap 
i'll also want to be a ccontrubutor to your repo

**Comment by petersdt** [comment]
@revengexd can i contribute to this

**Comment by martinvibes** [comment]
@revengexd @fricoben  let me deliver to this issue
did something like this last week on this repo #789

**Comment by Ugo-X** [comment]
please @fricoben and @revengexd can I be assigned this issue? I have a proven track record of efficiency and speed in delivering tasks.

**Comment by MullerTheScientist** [comment]
Hello @revengexd can I address this issue
I will Inspect the elements and sections where the cursor changes using the browser's developer tools.
and Check the CSS styling and JavaScript code for any inconsistencies or errors.

**Comment by Luluameh** [comment]
@revengexd  Can I be assign this issue

**Comment by GoSTEAN** [comment]
hello @revengexd please let me take on this issue and be a contributor to this repo

**Comment by harshal2608** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have been a lead FE dev for 2 years. Can I have this issue?

**Comment by MariangelaNM** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I'm Mariangela. I'm a software developer specializing in front-end development, and I would like to work on this project.

### How I plan on tackling this issue
1. **CSS Style Audit**: Conduct an audit of the CSS styles to identify any rules that may be applying undesired cursor changes.
2. **Event Review** : Review the `onhover`, `onmouseover`, or any other events related to user interaction to ensure they are not incorrectly manipulating the cursor.
3. **Load Optimization**: Evaluate the possibility of optimizing resource loading to prevent the cursor from changing while waiting for resources.
4. **A/B Testing**: Implement A/B testing to verify if changes to the styles or event handling resolve the issue without affecting the user experience.

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a fullstack web3 Next.js developer. Prior to working as a full stack dev, i was a frontend engineer for almost a year. I believe my frontend engineering skills can be used to solve this bug.

### How I plan on tackling this issue
1. Check out the components where the cursor is not acting as desired
2. CSS has a cascading functionality, hence check if any tailwind classes are present in the components which may conflict with the cursor design.
3. if the conflicting class is required for that component, explore alternative ways to fix the issue
4. Add comments to ensure any new contributor is able to understand
5. Test by running the repo and ensure no error/bugs occur due to my code
6. Final review before the PR

**Comment by ShantelPeters** [comment]
Can I be assigned to this issue ?

**Comment by melnikga** [comment]
Hi, can I take this?
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo.

### How I plan on tackling this issue
to address the issue of the cursor changing from the custom Starknet Quest pointer to the normal pointer when hovering over certain sections, I would start by reviewing the CSS and styles applied to the affected sections. I’d ensure that the classes or properties controlling the cursor style are correctly applied and not being overridden in those areas. I would also check for any conflicts with other styles or scripts that might be resetting the cursor. After adjusting the styles, I’d test the functionality to ensure the custom pointer remains consistent across all sections.

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi @revengexd,

I’m a Full Stack Developer with two years of experience, primarily working with Next.js. I’m excited to contribute to open source and eager to get involved with this project. Although this is my first time engaging with the open source community, I'm confident that my background in full stack development will enable me to make meaningful contributions. And I am also a member of dojo coding... I would appreciate the opportunity to work on this issue. Thank you for considering my request!



### How I plan on tackling this issue
To solve this issue, I will review the cursor CSS attribute of the affected components, such as the Tab component in the questAndCollectionTabs.tsx file, and apply the correct styles. After making the changes, I will ensure everything is functioning correctly.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

**Comment by MatiasAchucarro** [comment]
Hello @Marchand-Nicolas , where can I ask you some questions?

**Comment by Marchand-Nicolas** [comment]
https://github.com/starknet-id/starknet.quest/pull/824
