### ISSUE TITLE
Add "jediswap" to `AUDITED_APPS` on defi.ts

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#807]
Jediswap was audited by Nethermind in cairo 1 https://github.com/NethermindEth/PublicAuditReports/blob/main/NM0180-FINAL_JEDISWAP.pdf

So we need to update our `Earn` page by adding "jediswap" to `AUDITED_APPS` on defi.ts

**Comment by Iwueseiter** [comment]
Hi @fricoben can I work on this?

**Comment by raizo07** [comment]
@fricoben I'll like to work on this

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web3/Frontend developer

### How I plan on tackling this issue
I will update the `earn` page by adding jediswap to `AUDITED_APP` on defi.ts

**Comment by Jemiiah** [comment]
I’d love to work on this @fricoben

**Comment by Jemiiah** [comment]
I’d love to work on this @fricoben

**Comment by GoSTEAN** [comment]
i would love to take on this issue @fricoben

**Comment by petersdt** [comment]
@fricoben can i work on this

**Comment by Luluameh** [comment]
@fricoben I can handle this task , I will love to make this my first contribution to the starknet quest project.  kindly  assign me , if available

**Comment by mystical-prog** [comment]
I have opened up a PR for this issue - #811

**Comment by EmmanuelAR** [comment]
heyyy @fricoben can i work on this? i will 
	1.	Open defi.ts.
	2.	Find the AUDITED_APPS list.
	3.	Add “jediswap” to the list.
	4.	Save your changes.
	5.	Test the Earn page.
	6.	Commit and push changes.

**Comment by harshal2608** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have been contributing on jediswap for a long time. Can I have this issue?

**Comment by Crosstons** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience in javascript and typescript. 

### How I plan on tackling this issue
By adding "jediswap" to the AUDITED_APPS

**Comment by mystical-prog** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Starknet Quest contributor with overall understanding of the project and have experience with React/Next web apps for about 2 years now.

### How I plan on tackling this issue
By making changes under the defi.ts file in constants dir.

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a full stack developer primarily working on Next.js and web3 applications. I have contributed to open source dapps. Part from web3, I am also confident in my frontend and backend skills.

### How I plan on tackling this issue
1. Open constatnts/defi.ts
2. add "jediswap" to the AUDITED_APPS array.
3. Test the app to see it runs error free just like before my code
4. Make the final PR

**Comment by ShantelPeters** [comment]
Hi @fricoben can I work on this please

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi @fricoben,
I’m a Full Stack Developer with two years of experience, primarily working with Next.js.  
Thank you for considering my request!

### How I plan on tackling this issue
To address this issue, I will open the defi.ts file, add Jediswap to the AUDITED_APPS list, save the changes, and then test the Earn page.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.
