### ISSUE TITLE
Wrong sending router link

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#813]
## Demonstration

https://www.loom.com/share/6f13fbbe33324e87812e199de5a7294a?sid=1015387c-398f-4c33-a3ca-4066a5f97c9c

## Solution

On the `quest-boost/page.tsx`, instead of sending it back like `router.back()`.

We need to send it back to the starknet.quest home page directly using `router.push("/")`

**Comment by addegbenga** [comment]
Can I work on this.

**Comment by GoSTEAN** [comment]
hello @fricoben let me work on this issue

**Comment by EmmanuelAR** [comment]
hey @fricoben can i work on this? 
i will...
	1.	Open the quest-boost/page.tsx file: Navigate to this file in your project directory.
	2.	Find the router.back() command: Look for the part of the file where the code sends the user back to the previous page.
	3.	Replace router.back() with router.push("/"): Instead of sending the user back to the previous page, you’ll modify the command to redirect them directly to the Starknet.quest home page.
	4.	Save and Test: Save the changes and test the application to ensure that clicking the button or performing the action now correctly redirects the user to the homepage.

**Comment by Jemiiah** [comment]
Hello @fricoben I would love to work on this issue

**Comment by MariangelaNM** [comment]
Hi @fricoben,Can I work on this?

What we need to do in this issue is change how we're redirecting the user on the `quest-boost/page.tsx` page. Right now, we're using `router.back()`, which just takes them back to the last page they visited. But what we actually want is to send them directly to the Starknet Quest home page, no matter where they came from.

To do that, instead of using `router.back()`, we should use `router.push("/")`. This will ensure that the user is always redirected straight to the homepage.

**Comment by bitfalt** [comment]
Hii! I would love to work on this issue. I'm active OnlyDust contributor. I would tacke this issue in the following way:
Since the behaviour of the current code is to use router.back(), it takes the user to the last page they visited. Since the user goes to Quests Boosts -> Quests Boosts Claim -> Quests Boosts, the last page they visited is Quests Boosts Claim, therefore starting the endless loop.
- Identify the part of the code in `quest-boost/page.tsx` where the problem is
- Change the function so it returns to the main page, using `router.push("/")` 
- Check for any similar loops throughout the code
- Test the behaviour of the page, to make sure all the flows are working properly.

I would ask the maintainers if any questions come up during the implementation or for feedback regarding my code.

**Comment by ShantelPeters** [comment]
Hi @fricoben i will love to work on this issue?

**Comment by melnikga** [comment]
Hi, can I take this?
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I  am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding 🇨🇷

This won't take long to resolve, the longest time it would take would be to set up the project and get it working properly locally.

### How I plan on tackling this issue
1. Open the quest-boost/page.tsx file: Navigate to this file in your project directory.
2. Find the router.back() command: Look for the part of the file where the code sends the user back to the previous page.
3. Replace router.back() with router.push("/"): Instead of sending the user back to the previous page, you'll modify the command to redirect them directly to the Starknet.quest home page.
4. Save and Test: Save the changes and test the application to ensure that clicking the button or performing the action now correctly redirects the user to the homepage.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects. I started contributing to open source via onlydust in march this year and I have contributed to a couple of issues, you can see them in my profile.

### How I plan on tackling this issue
Change the route to go back to home page by using `router.push("/")`

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi @fricoben,
As I mentioned in other issue, I’m a Full Stack Developer with most of my experience in Next.js.

### How I plan on tackling this issue
To resolve this, as you mentioned in the quest-boost/page.tsx, the solution involves modifying the BackButton component. Specifically, the onClick function should be updated from router.back() to router.push("/").

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I’m a front-end developer transitioning to Web3 and I would love to make my first contribution.  I’m looking forward to applying my skills in this new space and contributing to the community.

### How I plan on tackling this issue
Check the section in quest-boost/page.tsx causing the issue.
Update the function to redirect to the main page using router.push("/").
Search the codebase for similar patterns or loops.
Test the page to confirm all flows function correctly.

**Comment by Zeegaths** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm exerienced with react

### How I plan on tackling this issue
I'll first go to the quest page and look for router.back and change it to router.push. Adjust and other parts of the codebase that are affected by this page, Deploy and test

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

Hello @FricoBen I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/  and  https://metacrypt.vercel.app/  showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

### How I plan on tackling this issue

To solve this,I will replace the router.back() method with router.push("/") in your quest-boost/page.tsx file. This will ensures that, instead of navigating back to the previous page, the user is directly redirected to the Starknet Quest homepage.
