### ISSUE TITLE
Make the whole line clickable on the `discover/defi` page

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#819]
## Video Description

https://www.loom.com/share/fb04920ef87247998a6243fde64dd5c6

In short, you'll need to make the whole line clickable so it's easier to navigate

**Comment by Ayoazeez26** [comment]
@fricoben can I work on this when the ODHack starts?

**Comment by GoSTEAN** [comment]
@fricoben Can I work on this

**Comment by martinvibes** [comment]
hello @fricoben can i be assigned to this when the ODHack starts as i have done something similar like on this repo

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a fullstack developer, primarily working on production level Next.js apps and web3.  I have contributed to many open source dapps too. Apart from web3, I am also confident in my frontend and backend skills.

### How I plan on tackling this issue
1. Go to components/discover/defiTable.tsx
2. Change the element containing the function to redirect to a new page on a new tab, so that now the element containing the entire row has that function and hence the whole row becomes clickable
3. Add comments to explain my code, and ensure proper readability
4. Test the page and eliminate any bugs that may have arised due to my code before final PR

**Comment by Naomi-Gift** [comment]
@fricoben Can I work on this issue?

**Comment by ahmadou-ai** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey ! I'm an passionate and experienced software engineer working currently in startup (AI field), but I'm growing a strong interest on web3 and espacially in starknet. It will be my first contribution, I would be glad to be involved in this very exciting project :) 

### How I plan on tackling this issue
I checked defiTable.tsx and saw that it is responsible for displaying data on quests in a table structure using the useReactTable hook. A further look inside the columns construction and I can see where is the action link. The solution is to set up this link directly where the rows component are rendered. 

I can crush it ASAP !

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi @fricoben,
I’m a Full Stack Developer with two years of experience, primarily working with Next.js. I’m excited to contribute to open source and eager to get involved with this project. Although this is my first time engaging with the open source community, I'm confident that my background in full stack development  will enable me to make meaningful contributions. And I am also a member of dojo coding... I would appreciate the opportunity to work on this issue. Thank you for considering my request!

### How I plan on tackling this issue
After reviewing the code, I believe the solution involves adding the onClick function to the TableRow component. I’ve tested this approach and created a video demonstration to show how it works. https://drive.google.com/file/d/1SSLNO43q-S0G3G2OBz4yofc-IEhCpIac/view?usp=sharing

**Comment by MullerTheScientist** [comment]
Hello @fricoben I want to address this issue

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor.

### How I plan on tackling this issue
This won't take long to resolve, the longest time it would take would be to set up the project and get it working properly locally.  

After reviewing the code we can add an Onclick event to the TableRow Component, and enable the opening of the entire row on the pag

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects. I started contributing to open source via onlydust in march this year and I have contributed to a couple of issues, you can see them in my profile.

### How I plan on tackling this issue
Make the whole line clickable by covering the whole line in an a tag or the appropriate tag that was used

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
As an experienced Full Stack Blockchain Developer, I'm excited to contribute my expertise to Edition 7 of the OnlyDust hackathons. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Solidity, and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 28 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we embark on Edition 7, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
With a passion for creating cutting-edge solutions, I'm excited to collaborate with the OnlyDust community and contribute to the advancement of the blockchain ecosystem.


### How I plan on tackling this issue
I would  make the whole line clickable as requested

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.
