### ISSUE TITLE
Some protocol links in earn which redirects to Liquidity are not working !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#888]
Details : https://www.loom.com/share/be453d8f9005412b980092a55dc7e6ca?sid=c462f38c-c145-40f6-a2b7-08ae0e9f8656

**Comment by Abeeujah** [comment]
Hi, I would love to work on resolving this.

**Comment by fricoben** [comment]
You need to add 

```ts
  haiko_solvers: {
    "Provide Liquidity": "https://app.haiko.xyz/positions",
  },
  ```
  
  to the `defi.ts` file in the const `linkMap`

**Comment by fricoben** [comment]
I assigned you @Abeeujah

**Comment by Abeeujah** [comment]
Okay, Thank you @fricoben will get that done, tested and make a Pull Request once I confirm that sorts it.

**Comment by Abeeujah** [comment]
Hi @fricoben @revengexd 

It looks like the issue is that Opus isn't defined in the linkMap within defi.ts, which is why getRedirectLink returns a blank URL.

After some lookups, I found the following:

- The official website listed for Opus on CoinMarketCap [Opus](http://opus-foundation.org/) redirects to an Indonesian website named `"ugliesttattoo"`
- Another website I found, opus.audio, appears inactive, with their last Twitter post dating back to 2021.
- The only liquidity pool related to Opus that I could find is hosted at [Chorus One](https://opus.chorus.one/pool/stake/), which doesn't seem like what you need.
