### ISSUE TITLE
Add OKX wallet

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#908]
## Description 

Following [this injection](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/utils/connectorWrapper.ts) model please add OKX wallet support to Starknet Quest.

**Comment by ikemHood** [comment]
Hey @fricoben , I'd love to work on this!

- add a new InjectedConnect in availableConnectors defined inside `app/provider.tsx`
- update wallets array with the OKX wallet details
- test the changes

**Comment by Otaiki1** [comment]
Hi I would love to work on this

**Comment by jaiminRaiyani** [comment]
Can I contribute to this one?

**Comment by MPSxDev** [comment]
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

**Comment by TEMHITHORPHE** [comment]
May I try my hand at this?.
This is a pretty straightforward task with an already provided template to follow,
Since I already have viem/WagmI knowledge, should be easy to follow through.
ETA: 6 hours.

**Comment by Emmanex01** [comment]
Can I take care of this issue?

**Comment by SoarinSkySagar** [comment]
## My background
gm @fricoben, I am Sagar Rana and I have a lot of experience developing Dapps and contributing to Starknet ecosystem. I would love to resolve and close this issue. 
## Proposed solution
I would follow the given model very closely and work inside the utils directory and make sure that it works before making the PR

## ETA: 1 Day
