### ISSUE TITLE
Add Bitget Wallet

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#909]
## Description 

Following [this injection](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/utils/connectorWrapper.ts) model please add Bitget wallet support to Starknet Quest.

**Comment by ooochoche** [comment]
@fricoben Can I work on this

**Comment by ikemHood** [comment]
May I be assigned to this?

**Comment by ShantelPeters** [comment]
Hi @fricoben please can I be assigned to this issue?

**Comment by Otaiki1** [comment]
Can I be assigned this ?

**Comment by jaiminRaiyani** [comment]
Would love to tackle this!

**Comment by MPSxDev** [comment]
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

**Comment by Emmanex01** [comment]
Can I jump on this task?

**Comment by SoarinSkySagar** [comment]
## My background
gm @fricoben, I am Sagar Rana and I have a lot of experience developing Dapps and contributing to Starknet ecosystem. I would love to resolve and close this issue. 
## Proposed solution
I would follow the given model very closely and work inside the utils directory and make sure that it works before making the PR.

## ETA: 1 Day

**Comment by jaiminRaiyani** [comment]
hi @fricoben  I'm working on this and since i'm new to this project i need further clarification on this task.

also i'm facing this connector issue can you help me to resolve this issue
![Screenshot 2024-10-26 152643](https://github.com/user-attachments/assets/6248b5cb-ee97-42ab-affe-679adcf3de2e)
