### ISSUE TITLE
Reorganized wallet pop-up to show uninstalled wallets last

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#932]
<img width="414" alt="Capture d’écran 2024-11-07 à 11 24 36" src="https://github.com/user-attachments/assets/c0be1375-c3ab-4168-9cd2-25dc6e821f38">

OKX and Bitget wallets are not installed and should then be showed in the last position instead of right after argent/braavos

You can reuse the `sortConnectors` function [here](https://github.com/lfglabs-dev/app.starknet.id/blob/c15caf3281e3a6916fc5e5922edc719097a2f04d/utils/connectorWrapper.ts#L31)

**Comment by 0xdevcollins** [comment]
I'd love to work on this!

**Comment by jaiminRaiyani** [comment]
Is it okay if I take this? as i have previously worked on this

**Comment by wheval** [comment]
hello, @fricoben!.

I’d love to work on this task.

ETA is 5 hours.

**Comment by ShantelPeters** [comment]
Hi @fricoben can I please work on this

**Comment by sajalbnl** [comment]
I'd like to take this issue.

**Comment by Shaarps** [comment]
I’d like to help with this.

**Comment by snehaa-eth** [comment]
I'd love to give this a go.

**Comment by mimisavage** [comment]
May I be assigned to this?

**Comment by caxtonacollins** [comment]
I'd like to take this issue.

**Comment by godekina** [comment]
I'd like to apply to this issue

**Comment by Michaelkingsdev** [comment]
Hello @fricoben 
Can i work on this one? It will be my first time contributing to this project.

**Comment by Benjtalkshow** [comment]
I'd love to work on this sir @fricoben .

**Comment by Aditya-040** [comment]
Let me try this one! I am a full stack developer and have experience in javascript and typescript

**Comment by ooochoche** [comment]
I am looking forward to contributing to this.

**Comment by tasneemtoolba** [comment]
Hello @fricoben , I'm very interested in contributing! it's a simple task, but it will help me familiarize myself with the code, because I want to contribute further in the project! I'm interested to be an active contributor!).

**Comment by Great7-dev** [comment]
Could I take a shot at this?

**Comment by genamol** [comment]
I'd love to give this a go.

**Comment by 0xDeon** [comment]
Could I try solving this?
I am a returning contributor to the project I can get this delievered in 24 hrs

**Comment by ivancano** [comment]
Is it okay if I take this?

**Comment by pheobeayo** [comment]
Can I start working on this?

**Comment by Villarley** [comment]
My Background and How It Can Be Leveraged
I am Santiago Villarreal Arley, a dedicated software developer with a keen interest in Web3 technologies and decentralized applications. Recently, I have worked on various projects, such as BuildMyEvent, an open-source blockchain initiative, that required meticulous problem-solving and strategic feature integration. I am passionate about creating well-organized code structures and optimizing user experience. I aim to bring these skills to the current challenge of connector sorting, ensuring efficient and user-friendly access to wallet options within the application.

How I Plan on Tackling This Issue
I’m excited to address the connector sorting issue to ensure a more organized and intuitive user experience in selecting Web3 wallets within the app. Here’s the approach I propose:

Function Refactoring:
I will leverage the existing sortConnectors function to make the sorting logic more flexible and adaptable. I’ll update it to conditionally place specific connectors, such as OKX and Bitget, at the end of the list when they’re not installed, preserving the intended order.

Conditional Sorting Logic:
The function will be modified to:

Identify connectors like OKX and Bitget by their unique identifiers.
Place them at the end of the list only when their available() method returns false.
Otherwise, maintain the default order based on availability.

Code Readability and Documentation:
To maintain code clarity, I’ll add inline comments explaining the purpose and reasoning behind the conditional sorting. This will help in future maintenance and ensure other developers can quickly understand the logic.

Expected Benefits
This update will enhance user experience by presenting a cleaner and more predictable list of wallet options, improving usability and reducing potential confusion. Additionally, by reusing and refining existing code, the solution will align with project standards, maximizing maintainability and consistency.

I look forward to applying this structured solution and contributing to a more streamlined and user-centric application experience!

**Comment by Akshola00** [comment]
Is it okay if I take this?

**Comment by vestor-dev** [comment]
hey @fricoben can i hop on this issue??
would like to be a contributor

**Comment by KevinLatino** [comment]
Hi @fricoben,

I’m Kevin Latino, a frontend developer and a Dojo Coding Member.

I’ll complete this issue in 3 hours.

To resolve it, I’ll adjust the wallet sorting logic to ensure uninstalled wallets, specifically OKX and Bitget, appear last in the wallet list of the pop-up. By reusing the existing sortConnectors function, I’ll make sure that installed wallets like Argent and Braavos appear first, while uninstalled wallets are moved to the end.

Although I’m a contributor, my contribution was just adding an image. I’d now love to contribute with some actual code! :)

**Comment by 0xshubhs** [comment]
I’m interested in this one.

**Comment by GradleD** [comment]
Mind if I take this issue?

**Comment by fricoben** [comment]
@Villarley assigned to you :)

**Comment by Villarley** [comment]
> @Villarley assigned to you :)

Thank you so much, I'm working on it!🤲
