### ISSUE TITLE
Update `components/quests/questBanner.tsx` to no longer use JSON

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#986]
## Description 📹

**Update `components/quests/questBanner.tsx` to no longer use a JSON file (`questbanners.json`) and instead rely on a `banner` object passed as a prop. Update `questDetails.tsx` to replace `<QuestBanner questId={questId} />` with `<QuestBanner banner={quest.banner} />`.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

   Update `QuestBanner` to use a `banner` object instead of looking up the JSON file:
   - Update the props for the `QuestBanner` component to accept a `banner` object instead of `questId`.
   - Remove references to `useMemo` and the `questBanners` JSON file.
   - Adjust the JSX to use the fields from the `banner` prop directly.

   Update the `questDetails.tsx` file:
   - Replace `<QuestBanner questId={questId} />` with `<QuestBanner banner={quest.banner} />`.

   Updated code snippets:

   **`components/quests/questBanner.tsx`:**
   ```tsx
   import { FunctionComponent } from "react";
   import styles from "@styles/quests.module.css";
   import Button from "@components/UI/button";

   type Banner = {
     image: string;
     tag?: string;
     title: string;
     description: string;
     href: string;
     cta: string;
   };

   type QuestBannerProps = {
     banner: Banner;
   };

   const QuestBanner: FunctionComponent<QuestBannerProps> = ({ banner }) => {
     return (
       <div className={styles.questBanner}>
         <div
           className={styles.questBannerImage}
           style={{ backgroundImage: `url(${banner.image})` }}
         />
         <div className={styles.questBannerContent}>
           <h2 className={styles.questBannerTitle}>
             {banner.tag ? (
               <span className={styles.bannerTag}>{banner.tag} - </span>
             ) : null}
             {banner.title}
           </h2>
           <p>{banner.description}</p>
           <div className="w-fit">
             <Button
               onClick={() => {
                 window.open(banner.href, "_blank");
               }}
             >
               {banner.cta}
             </Button>
           </div>
         </div>
       </div>
     );
   };

   export default QuestBanner;
   ```

   **`components/quests/questDetails.tsx`:**
   ```tsx
   import QuestBanner from "./questBanner";

   // Existing code...

   return (
     <div>
       {/* Replace questId with quest.banner */}
       <QuestBanner banner={quest.banner} />
     </div>
   );
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Refactor QuestBanner to use banner object instead of questId"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Michaelkingsdev** [comment]
Let me work on this please. I can handle this task and make PR in 24hrs. Thanks

**Comment by Benjtalkshow** [comment]
Can i be assigned to this @Marchand-Nicolas ?

**Comment by Emmanex01** [comment]
Can I try solving this issue?
I'm Emmanuel Tochukwu, a software developer. I have experience building projects using Typescript and JavaScript.I would appreciate it if given the opportunity to contribute to this issue.

**Comment by wheval** [comment]
Hello @Marchand-Nicolas, I'm Wheval an experienced frontend developer.

Can i fix this issue?
I would ensure to update questBanner.tsx to accept the 'banner' object props not JSON.
I would also test it to ensure it works perfectly.

ETA is 1 day.

**Comment by KeneePatel** [comment]
Hello Nico,

I am a returning contributor to OnlyDust. I have previously completed several issues on a wide range of projects. The notable ones being kakarot and starknet.js. I will review and follow the community and contributing guidelines making sure the requirements are met properly.

This issue goes hand in hand with https://github.com/lfglabs-dev/api.starknet.quest/issues/348 
I have good experience working on NextJS with Typescript, therefore I will make sure the functionality will be modified properly.

ETA: 1d (in sync with the other issue)
Telegram: @patelkenee

**Comment by Supa-mega** [comment]
hi, May I take care of this?

**Comment by Ibinola** [comment]
Can I jump on this task?

Hi, I'm Michael, I'm a frontend developer with experience using React, Next.js and TypeScript and I'm also skilled at creating intuitive and responsive user interfaces, ensuring a seamless experience for users.

Relevant experience contributing to open-source projects where I used the technologies mentioned above ([Pear AI](https://github.com/trypear/pear-landing-page/pulls?q=author%3AIbinola) and [SpotNet](https://github.com/djeck1432/spotnet/pull/235)).  

Plan for Tackling the Issue
* Update the QuestBanner to use an object instead of the JSON 
* Remove the references to the JSON
* Adjust the JSX to use the fields from the banner prop directly.
* Test properly before pushing

**Comment by Jagadeeshftw** [comment]
May I handle this issue?

**Comment by portableDD** [comment]
I’d like to help with this. Hi, I am Emmanuel Dorcas, a software developer with React js and Typescript. my estimated timeframe is 1 day.

how I will tackle this:
1. I will fork the repository and create a new branch name fix-#986
2. update the components/quests/questBanner.tsx components.
3, create a interface banner.
4. I will update the questDetails.tsx with this <QuestBanner banner={quest.banner} />.
5. I test that all is working
6. then I push to the new branch.
7. then I create a pr giving it a description of Close #979.
8. then I change the label to 'ready for review"

**Comment by jahrulezfrancis** [comment]
I’d love to work on refactoring QuestBanner to use a banner object instead of relying on a JSON file. This will be my first contribution to Starknet Quest. My approach will involve updating the component to accept the banner as a prop and replacing references to the JSON file with direct usage of the prop fields. I’ll also update questDetails.tsx to ensure seamless integration.
ETA: 24 hours

**Comment by PedroCo3lho** [comment]
I'd like to take this issue.
I'm a full-stack developer with a solid understanding of Typescript, Next.Js, TailwindCSS, and API's. I've already contribute to starknet.quest implementing new feats, I'm familiar with the code base.
Please let me know if I can start so I can deliver then new requirement asap!

**Comment by Agbeleshe** [comment]
I'd like to take this issue.  I will start by updating the `QuestBanner` component to accept a `banner` object as a prop. I will refactor the component to remove all references to the JSON file (`questbanners.json`) and the `useMemo` logic for fetching data. The new implementation will directly use the `banner` prop for rendering. In `questDetails.tsx`, I will modify the code to replace `<QuestBanner questId={questId} />` with `<QuestBanner banner={quest.banner} />`, ensuring that the `banner` object is passed correctly. After implementing these changes, I will test the components locally to verify that the banner displays as expected across all scenarios and does not break existing functionality. Once confirmed, I will commit the changes with a descriptive message and submit a pull request with the appropriate label for review.

**Comment by BigBen-7** [comment]
Please can I take this issue??

**Comment by BigBen-7** [comment]
Please may I solve this issue?
If assigned to resolve the issue, I would start by updating the 'QuestBanner' component to accept a 'banner' object as a prop instead of referencing 'questbanners.json'. Remove all logic related to loading the JSON file and `useMemo`. Adjust its JSX to use the 'banner' object's fields directly. In 'questDetails.tsx', replace '<QuestBanner questId={questId} />' with '<QuestBanner banner={quest.banner} />'. After making these changes, test the functionality and ensure it works as expected without relying on the JSON file.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by OWK50GA** [comment]
### **I CAN SOLVE THIS ISSUE**

Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

My approach:
I will go into the Quest Banner.tsx file, and look for where the questId is gotten from, which is being passed to the component to render the quest banner. I will then look at the necessary props and their data types, and make a type definition of it on top of the QuestBanner component. 
After this, I will receive the props in the component of the type I just defined, and I will consume it throughout the component, rendering the necessary things. 
I will then to to where the QuestBanner.tsx itself is rendered, and change the narrative to receive the correct object. 

Expect my first PR within 24 hours of assignments.

**Comment by Amarjeet325** [comment]
May I take care of this?

**Comment by davedumto** [comment]
Hi,

My name is David, and I am a frontend developer skilled in TypeScript, JavaScript, React.js, and Next.js also I am experienced with Tailwind-css. As a new contributor, I’m eager to refactor the QuestBanner component to use the banner prop instead of questBanners.json and update questDetails.tsx accordingly.
I’ll ensure all changes are implemented, tested, and completed within 3 business days, following project guidelines. ETA 2days

Looking forward to contributing!

**Comment by Nityam573** [comment]
Could I take on this issue?

**Comment by sonkiee** [comment]
Can I start working on this?

**Comment by psychemist** [comment]
Hello, StarQuest project maintainers! 
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience building backend systems, implementing user authentication, and serving web resources over a fully fleshed-out and documented API. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

Over my years of experience, I have worked with tools like:
- Web3: Solidity and Rust
- Backend: Express.js, Nest.js, Django, FastAPI, and Flask
- Frontend: HTML/CSS, JavaScript/TypeScript, , React.js, Next.js, TailwindCSS, and shadcn/ui

Here is how I would solve this issue:

- First, I will update QuestBanner to accept a banner object as a prop instead of relying on questId or the questBanners JSON file.
- Then, I will remove unnecessary references to useMemo and the JSON file, and modify the JSX to directly use fields from the banner prop.
- Next, I will modify questDetails.tsx to replace <QuestBanner questId={questId} /> with <QuestBanner banner={quest.banner} />, ensuring it passes the correct banner object.
- Afterward, I shall write tests to check for proper serialization and deserialization of the banner field, covering cases where it is present and absent.
- Then, I will review and adjust any related code to support the updated QuestDocument structure and adhere to the codebase conventions.

I aim to complete this task within 48 hours being assigned and setting up my development environment, with my first pull request submitted before 24 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by psychemist** [comment]
Hello, StarknetQuest project maintainers! 
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience building backend systems, implementing user authentication, and serving web resources over a fully fleshed-out and documented API. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

Over my years of experience, I have worked with tools like:

Web3: Solidity and Rust
Backend: Express.js, Nest.js, Django, FastAPI, and Flask
Frontend: HTML/CSS, JavaScript/TypeScript, , React.js, Next.js, TailwindCSS, and shadcn/ui

Here is how I would solve this issue:

- First, I will update QuestBanner to accept a banner object as a prop instead of relying on questId or the questBanners JSON file.
- Then, I will remove unnecessary references to useMemo and the JSON file, and modify the JSX to directly use fields from the banner prop.
- Next, I will modify questDetails.tsx to replace <QuestBanner questId={questId} /> with <QuestBanner banner={quest.banner} />, ensuring it passes the correct banner object.
- Afterward, I shall write tests to check that hte banner object is handled appropriately as a prop to the QuestBanner component.
- Then, I will review and adjust any related code to support the updated QuestBanner component and adhere to the codebase conventions.

I aim to complete this task within 48 hours being assigned and setting up my development environment, with my first pull request submitted before 24 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by helios492** [comment]
Hello! @Marchand-Nicolas
As an experienced fullstack and blockchain developer, I am sure that I can satisfy you with this issue.
I am proficient in state management and also have strong background in problem solving skills.
I can handle this project within 3 business day and you will get what you want.
Thank yo for considering my opportunity and will look forward to your contact.
Best Regards.

**Comment by omsant02** [comment]
I would like to work on this issue

My Approach
I'll refactor QuestBanner to use banner props instead of JSON file and update the questDetails component accordingly.

ETA : 4 hrs

**Comment by 1nonlypiece** [comment]
I'd like to take this issue.

**Comment by Crosstons** [comment]
Can I tackle this one?

**Comment by 3th-Enjay** [comment]
Hello I have a proper understanding of this issue and how to go about it

**Comment by mimisavage** [comment]
May I take care of this?

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Cairo.

I will like to take care of this. Will follow the above requirements and create a good PR within 24hours.

**Comment by aurlic** [comment]
hey I would love to be able to resolve this issue ! This would be my first issue on Starknet Quest and i would be glad to contribute ! Thanks in advance

**Comment by KeneePatel** [comment]
Thank you for assigning me the issue. Just had a look at this, but will need some patience as I have an exam in a few hours. Will complete the issue right after ASAP!

**Comment by Marchand-Nicolas** [comment]
> Thank you for assigning me the issue. Just had a look at this, but will need some patience as I have an exam in a few hours. Will complete the issue right after ASAP!

No problem, good luck for your exams!
